name: todo app infra

run-name: terraform init plan & apply to ${{ inputs.environments }} by @${{ github.actor }}
 
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
      - 'features/*'
  workflow_dispatch:
    inputs:
      environments:
        description: "select environments"
        required: true
        default: dev
        type: choice
        options: [dev, qa, prod]
        

jobs:
  Scanning:
    name: Scanning Job
    runs-on: jeet-runner
    environment: dev
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        
      - name: Tfsec Scanning
        run: |
          echo "Tfsec Scanning...."
          tfsec .

      - name: Checkov Scanning
        run: |
          echo "Checkov Scanning...."
          checkov -d
         
      - name: trivy Scanning
        run: |
          echo "Trivy Scanning...."
          trivy config --terraform

 

  terraform:
    name: terraform init validate fmt & plan
    runs-on: jeet-runner
    

        

