name: todo app infra

run-name: terraform init plan & apply to ${{ inputs.environments }} by @${{ github.actor }}

on:
  push:
    branches:
      -main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      -main
  workflow_dispatch:
    inputs:
      environments:
        description: "select environments"
        required: true
        default: dev
        type: choice
        options: [dev, qa, prod]
  schedule:
    - cron: "0 2 * * *" # india time morning 7:30AM

jobs:
  terraformInitValidateandFmt:
    name: terraform init validate & fmt
    runs-on: jeet-runner
    environment: dev
    steps:
      - run: echo hello chaudhary shahab

